name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy hook
        run: curl ${{secrets.RENDER_DEPLOY_HOOK}}
